import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

import SideNav from "@/components/ui/sideNav";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            {/* Google Material Symbols */}
            <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
            />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="min-h-screen bg-zinc-50 font-sans">
            <div className="flex">
                <aside className="w-64 min-h-screen border-r border-zinc-200">
                    {/* Global SideNav - client component */}
                    <SideNav
                        items={[
                            {label: 'Summary', href: '/summary', icon: 'insights'},
                            {label: 'Phase 2', href: '/phase_two', icon: 'looks_two'},
                            {label: 'Phase 1', href: '/phase_one', icon: 'looks_one'},
                            {label: 'Reports', href: '/reports', icon: 'article'},
                            {label: 'Useful Links', href: '/settings', icon: 'link'},

                        ]}
                    />
                </aside>

                <main className="flex-1 h-screen overflow-y-auto p-4">
                    {children}
                </main>
            </div>
        </div>
        </body>
        </html>
    );
}
